package com.pearson.snake.entity;

public enum Food {
  PINKY_MOUSE, FUZZY_MOUSE, HOPPER_MOUSE, SMALL_MOUSE, ADULT_MOUSE, JUMBO_MOUSE, PINKY_RAT, FUZZY_RAT, SMALL_RAT, MEDIUM_RAT, LARGE_RAT, JUMBO_RAT, OTHER;
}
