package com.pearson.snake.entity;

public enum SnakeSpecies {
  PYTHON_REGIUS, PANTHEROPHIS_GUTTATUS, BOA_CONSTRICTOR, HETERODON_NASICUS, GONGYLOPHIS_COLUBRINUS, EPICRATES_CENCHRIA, MALAYOPYTHON_RETICULATUS, MORELIA_SPILOTA, OTHER
}
